# Don't print a new line at the start of the prompt
add_newline = false

#format = "$time$directory[î‚°](fg:#303030 bg:#afd700)$git_branch[î‚°](fg:#afd700 bg:#7084f5)$kubernetes[î‚°](fg:#7084f5)$line_break $character"
format = "$time[î‚°](fg:#303030 bg:#7084f5)[ ](bg:#7084f5)$kubernetes[ ](bg:#7084f5)[î‚°](fg:#7084f5 bg:#afd700)[ ](bg:#afd700 fg:#7084f5)$git_branch$git_status[ ](bg:#afd700 fg:#7084f5)[î‚°](fg:#afd700 bg:#303030)[ ](bg:#303030 fg:#9e9e9e)$directory[ ](bg:#303030 fg:#9e9e9e)[î‚°](fg:#303030)$line_break $character"
#format = "î‚° ï˜ î‚° stacks î‚°âŸª[$git_branch](bold red) ğŸ§âŸ« $kubernetes $directory $line_break $character"
# Replace the "â¯" symbol in the prompt with "âœ"
[character]      # The name of the module we are configuring is "character"
symbol = "âœ"     # The "symbol" segment is being set to "âœ"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[directory]
truncation_length = 2
truncation_symbol = "â€¦/"
format = "[$path](bg:#303030 fg:#9e9e9e)"

[git_branch]
symbol = "ğŸŒ± "
truncation_length = 8
truncation_symbol = ""
format = "[$symbol$branch](bg:#afd700 fg:#005f00)"

[git_commit]
commit_hash_length = 4

[git_state]
progress_divider = " of "
cherry_pick = "ğŸ’ PICKING"

[git_status]
#conflicted = "ğŸ³"
#ahead = "ğŸğŸ’¨"
#behind = "ğŸ˜°"
#diverged = "ğŸ˜µ"
untracked = "ğŸ¤·"
stashed = "ğŸ“¦"
#modified = "ğŸ“"
#staged.value = "++"
#staged.style = "green"
staged_count.enabled = true
#staged_count.style = "green"
renamed = "ğŸ‘…"
#deleted = "ğŸ—‘"
format = '([\[$all_status$ahead_behind\]]($style))'
style = "bg:#afd700 fg:#005f00"

#[golang]
#symbol = "ğŸğŸ’¨ "

#[hostname]
#ssh_only = false
##prefix = "âŸª"
##suffix = "âŸ«"
#format = "âŸª[$hostname](bold red)âŸ«"
#trim_at = ".companyname.com"
#disabled = false

[kubernetes]
#symbol = "â˜¸ï¸"  
style = "bg:#7084f5 fg:#303030"
disabled = false
format = "[$context î‚± $namespace]($style)"
[kubernetes.context_aliases]
"dev.local.cluster.k8s" = "mydev"
"kubernetes-admin@Sapienza-Staging" = "sapstaging"
"kubernetes-admin@Sapienza-Production" = "sapprod"

[memory_usage]
disabled = true
show_percentage = true
show_swap = true
threshold = -1
symbol = " "
separator = "/"
style = "bold dimmed green"

[time]
disabled = false
format = "[ğŸ•™](bg:#303030 fg:#9e9e9e)[ $time ](bg:#303030 fg:#9e9e9e)"
utc_time_offset = "local"
#time_range = "6:00:00-20:00:00"

